# Command shortcuts
alias c    copy
alias d    delete
alias e    edit
alias f    find
alias g    goto
alias h    help
alias l    list
alias m    move
alias p    print
alias q    quit
alias r    read
alias w    write
alias sh   shell

# Unix compatibility
alias cd   goto
alias cp   copy
alias echo print
alias exit quit
alias ls   list
alias mv   move
alias rm   delete
